### ISSUE TITLE
tests are failing, why publish?

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/benchmarked#5]
even examples fail.

```
[charlike@voltaire benchmarked]$ node example.js 
Benchmarking: (1 of 1)
 · short

# examples/fixtures/short.txt (3 bytes)
  while x 6,725,933 ops/sec ±1.46% (57 runs sampled)
  slice x 4,780,844 ops/sec ±1.12% (65 runs sampled)

/home/charlike/dev/final/benchmarked/index.js:304
    console.log('  fastest is', colors.green(this.filter('fastest').pluck('name')));
                                                                    ^

TypeError: this.filter(...).pluck is not a function
    at Suite.<anonymous> (/home/charlike/dev/final/benchmarked/index.js:304:69)
    at /home/charlike/dev/final/benchmarked/node_modules/benchmark/benchmark.js:1212:40
    at arrayEach (/home/charlike/dev/final/benchmarked/node_modules/lodash/lodash.js:498:11)
    at Function.forEach (/home/charlike/dev/final/benchmarked/node_modules/lodash/lodash.js:8382:11)
    at Suite.emit (/home/charlike/dev/final/benchmarked/node_modules/benchmark/benchmark.js:1211:11)
    at Suite.invoke.onComplete (/home/charlike/dev/final/benchmarked/node_modules/benchmark/benchmark.js:1183:17)
    at getNext (/home/charlike/dev/final/benchmarked/node_modules/benchmark/benchmark.js:897:30)
    at execute (/home/charlike/dev/final/benchmarked/node_modules/benchmark/benchmark.js:859:26)
    at invoke (/home/charlike/dev/final/benchmarked/node_modules/benchmark/benchmark.js:967:20)
    at Suite.runSuite [as run] (/home/charlike/dev/final/benchmarked/node_modules/benchmark/benchmark.js:1166:7)
```

**Comment by tunnckoCore** [comment]
i can't create PR to add support for async benchmarking before we fix issues

**Comment by jonschlinkert** [comment]
This kind of issue makes me want to start publishing my code to private repos.

**Comment by tunnckoCore** [comment]
Haha, why? I just tried examples locally and then clone the repo and tried the tests.

I've needed benchmarking these days and switched to use directly benchmark.js, because the lack of support for async benchmarking.

**Comment by jonschlinkert** [comment]
Because I just refactored the repository completely. Tests were passing locally. I pushed up and travis failed the tests. I have no idea why and I haven't had time to look, but I followed semver. IMHO when a lib is completely refactored it's not shocking when some bugs need to be flushed out. The only way to do that sometimes is to publish the code and get feedback from other users.

To be 100% honest, I avoided doing this for a while b/c I didn't feel like getting in a debate about my decisions on this project. It's something I use for quick feedback when making code decisions on **simple microlibs**. My use case is obviously different than yours. I would use benchmark directly for advance stuff. Nonetheless, why can't you do async with this if you wan to? you can access the benchmark object on the instance, you can pass options, you can customize virtually anything on it.

**Comment by tunnckoCore** [comment]
Yes I can, not that's the problem. The problem and this issue is for that it completely not works currently, not only on travis. Just wanted to ping that :)
